import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/components/header";
import { AppSidebar } from "@/components/app-sidebar";
import Providers from "@/store/providers/providers";
import { authUser } from "@/lib/auth";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 토큰 유효성 검사
  const auth = await authUser();

  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute={"class"} // Tailwind css dark: 클래스를 자동으로 적용
          defaultTheme="system" // OS 설정 모드를 기본화
          enableSystem // 시스템 모드 감지 활성화
          disableTransitionOnChange
          storageKey="theme" // 로컬 스토리지에 저장할 name
        >
          <Providers>
            <SidebarProvider>
              <div className="flex h-screen w-full">
                <AppSidebar />
                <div className="flex flex-1 flex-col">
                  <Header auth={auth} />
                  <main className="flex-1">{children}</main>
                </div>
              </div>
            </SidebarProvider>
          </Providers>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
